"""Cross-language canonicalization vectors (P1.1 §11): these bytes must
be identical to the gateway's internal/identity/canon.go output — the
matching assertions live in canon_vectors_test.go."""

from __future__ import annotations

import base64

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
)

from ovara_sdk.canon import hop_payload, lease_payload

# Generated by the Go implementation; asserted byte-identical here.
HOP1 = (
    "000000086973737565722d310000000661675f6162630000000467772d41"
    "0000001868747470733a2f2f6170692e6769746875622e636f6d2f2a000000"
    "02000000057368656c6c0000000465786563000000006553f1000000000064"
    "bb5a80000000096e2d66697865642d3100000000"
)
HOP2 = (
    "000000146973737565722dc3bc6ec3af636f64652de6a0b90000000c61675f"
    "e697a5e69cace8aa9e00000000000000012a00000000fffffff1886e090000"
    "000000000000000000000000000000"
)
LEASE = (
    "000000056c73655f31000000056f766172610000000661675f616263000000"
    "0467772d4100000001000000057368656c6c0000000c7265706f3a2f2f6f72"
    "672f2a000000006553f1000000000064bb5a8000000002"
)


def test_hop_vector_simple() -> None:
    got = hop_payload(
        "issuer-1", "ag_abc", "gw-A", "https://api.github.com/*",
        ["shell", "exec"], 1700000000, 1690000000, "n-fixed-1", "",
    )
    assert got.hex() == HOP1


def test_hop_vector_unicode_empty_optional() -> None:
    got = hop_payload(
        "issuer-ünïcode-根", "ag_日本語", "", "*", None, -62135596800, 0, "", "",
    )
    assert got.hex() == HOP2


def test_lease_vector() -> None:
    got = lease_payload(
        "lse_1", "ovara", "ag_abc", "gw-A", ["shell"], "repo://org/*",
        1700000000, 1690000000, 2,
    )
    assert got.hex() == LEASE


def test_signatures_are_unambiguous() -> None:
    """The F-7 collisions must now produce DIFFERENT signed bytes."""
    a = hop_payload("i", "s", "", "", ["a b"], 0, 0, "", "")
    b = hop_payload("i", "s", "", "", ["a", "b"], 0, 0, "", "")
    assert a != b  # ["a b"] vs ["a","b"] — was the %v collision

    c = hop_payload("x|y", "z", "", "", None, 0, 0, "", "")
    d = hop_payload("x", "y|z", "", "", None, 0, 0, "", "")
    assert c != d  # pipe in a field can't shift field boundaries


def test_python_signed_hop_verifiable() -> None:
    """The exact chain Go's TestCanon_PythonSignedChainVerifies checks."""
    seed = bytes(range(32))
    priv = Ed25519PrivateKey.from_private_bytes(seed)
    pub = priv.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw
    )
    assert pub.hex() == (
        "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
    )
    payload = hop_payload(
        "issuer-py", "ag_py", "gw-A", "repo://org/*",
        ["shell"], 4102444800, 1690000000, "py-nonce-1", "",
    )
    sig = priv.sign(payload)
    assert base64.b64encode(sig).decode() == (
        "c9Yeq/w6YyW13j1ZZ/TkcIMygQCY6zkgqK/MfjPe5yJUM68lpfmQNnN/f50WTNB/"
        "bJDCrYCfwx1BDbaNcZEIBw=="
    )
